### ISSUE TITLE
requirements for installation?

### ISSUE THREAD

**Issue by jbloom** [harmslab/epistasis#38]
Right now installation of `epistasis` with `pip` requires exact versions of all the dependencies, as they are pinned to specific versions in `requirements.txt` (https://github.com/harmslab/epistasis/blob/master/requirements.txt).

This makes it a pain to install in environments with other Python packages, as sometimes it is rolling back newer versions of dependencies to get the precise older pinned version for `epistasis`.

Would it be possible to change these requirements to simply indicating the minimal required version unless there really is a need to have an exact version?

This appears to be what is recommended by the Python packaging guide; see near the end of the first subsection of this page:
https://packaging.python.org/discussions/install-requires-vs-requirements/

**Comment by Zsailer** [comment]
Yes, we should definitely relax these requirements. Sorry about that! I was using `pipenv` to manage the development environment and write out the requirements to file. I didn't realize it actually pinned the requirements to exact versions. 

I've opened #40 to fix this issue.

**Comment by Zsailer** [comment]
Merging the PR auto-closed this issue. 

If you are still having issues with the dependencies, let us know.
