### ISSUE TITLE
Slack app

### ISSUE THREAD

**Issue by jbloom** [harmslab/epistasis#42]
Would you be willing to install the Slack app for the `epistasis` repository? This would enable us to set Slack updates when the repo is updated. See attached.
<img width="679" alt="Screen Shot 2019-03-22 at 12 46 58 PM" src="https://user-images.githubusercontent.com/1906801/54849220-d8f62880-4ca0-11e9-82aa-3eb801689d60.png">

**Comment by Zsailer** [comment]
Ok, I think I installed the Slack app... This technology stuff is hard.

Can you try subscribing to this repo and let me know? I've also enabled slack for the `gpmap` repo.

**Comment by jbloom** [comment]
Worked great, thanks!
